# author --> Skye Lane Goetz

babel: /local_raid1/sgoetz/DBSTORE/TBDB/DERIVATIVES/BABEL.db
pubmed: /local_raid1/sgoetz/DBSTORE/TBDB/DERIVATIVES/PubMed.db
pmc_captions: /local_raid1/sgoetz/DBSTORE/TBDB/DERIVATIVES/PMCSuppCaptions.db