-- CONFIGURE DB SETTINGS
PRAGMA journal_mode=WAL;
PRAGMA synchronous=OFF;
PRAGMA foreign_keys=OFF;
PRAGMA locking_mode=EXCLUSIVE;

-- CONFIGURE DB FOR INGESTION
BEGIN IMMEDIATE;
-- DROP UNESSECARY TABLES
DROP TABLE IF EXISTS [acc];
DROP TABLE IF EXISTS [type];
-- DROP UNESSECARY COLUMNS
ALTER TABLE [mesh] DROP COLUMN [pmcid];
ALTER TABLE [mesh] DROP COLUMN [qual];
ALTER TABLE [mesh] DROP COLUMN [qual_major];
ALTER TABLE [info] DROP COLUMN [section];
-- DROP INDEXES FOR FASTER TRANSFER
DROP INDEX IF EXISTS [idx_mesh_pmid];
DROP INDEX IF EXISTS [idx_mesh_mesh];
DROP INDEX IF EXISTS [idx_ids_pmid];
DROP INDEX IF EXISTS [idx_ids_alt];
-- RENAME TABLES FOR POSTGRES SCHEMA
ALTER TABLE [mesh] RENAME TO [MESH];
ALTER TABLE [info] RENAME TO [INFO];
ALTER TABLE [ids] RENAME TO [IDS];
-- RENAME COLUMNS FOR POSTGRES SCHEMA
ALTER TABLE [MESH] RENAME COLUMN [pmid] TO [PMID];
ALTER TABLE [MESH] RENAME COLUMN [mesh] TO [MESH];
ALTER TABLE [MESH] RENAME COLUMN [mesh_major] TO [MESH_MAJOR];
ALTER TABLE [INFO] RENAME COLUMN [pmid] TO [PMID];
ALTER TABLE [INFO] RENAME COLUMN [firstauthor] TO [FIRST_AUTHOR];
ALTER TABLE [INFO] RENAME COLUMN [year] TO [YEAR];
ALTER TABLE [INFO] RENAME COLUMN [journal] TO [JOURNAL];
ALTER TABLE [INFO] RENAME COLUMN [title] TO [TITLE];
ALTER TABLE [IDS] RENAME COLUMN [pmid] TO [PMID];
ALTER TABLE [IDS] RENAME COLUMN [alt] TO [ALT];
-- COMMIT CHANGES
COMMIT;

-- OPTIMIZE DB AND FREE UP SPACE
ANALYZE;
PRAGMA optimize;
VACUUM;