-- TURN ON FOREIGN KEYS
PRAGMA foreign_keys=ON;

-- CONFIGURE DB FOR INGESTION
BEGIN IMMEDIATE;
-- COPY PUBMED TABLES
CREATE TABLE [MESHTERMS] AS SELECT * FROM PUBMED.[MESHTERMS];
CREATE TABLE [INFORMATION] AS SELECT * FROM PUBMED.[INFORMATION];
CREATE TABLE [IDENTIFIERS] AS SELECT * FROM PUBMED.[IDENTIFIERS];
-- COPY PMC_CAPTIONS TABLES
CREATE TABLE [PMCCAPTIONS] AS SELECT * FROM PMC_CAPTIONS.[PMCCAPTIONS];
-- RENAME TABLES I'M UPDATING
ALTER TABLE [CATEGORIES] RENAME TO [CATEGORIES_OLD];
ALTER TABLE [NAMES] RENAME TO [NAMES_OLD];
ALTER TABLE [SYNONYMS] RENAME TO [SYNONYMS_OLD];
ALTER TABLE [MESHTERMS] RENAME TO [MESHTERMS_OLD];
ALTER TABLE [INFORMATION] RENAME TO [INFORMATION_OLD];
ALTER TABLE [IDENTIFIERS] RENAME TO [IDENTIFIERS_OLD];
ALTER TABLE [PMCCAPTIONS] RENAME TO [PMCCAPTIONS_OLD];
-- DEFINE UPDATE TABLES AND COPY OLD VALUES INTO THEM
CREATE TABLE [CATEGORIES] (
    [ID] INTEGER PRIMARY KEY,
    [NAME] TEXT
);
INSERT INTO [CATEGORIES] ([ID], [NAME]) SELECT [ID], [NAME] FROM [CATEGORIES_OLD];
CREATE TABLE [NAMES] (
    [ID] INTEGER PRIMARY KEY,
    [CURIE] TEXT,
    FOREIGN KEY [CATEGORY] INTEGER REFERENCES [CATEGORIES]([ID]),
    [NAME] TEXT,
    [TAXON] INTEGER
);
INSERT INTO [NAMES] ([ID], [CURIE], [CATEGORY], [NAME], [TAXON]) SELECT [ID], [CURIE], [CATEGORY], [NAME], [TAXON] FROM [NAMES_OLD];
CREATE TABLE [SYNONYMS] (
    FOREIGN KEY [ID] INTEGER REFERENCES [NAMES]([ID]),
    [L1] TEXT,
    [L3] TEXT
);
INSERT INTO [SYNONYMS] ([ID], [L1], [L3]) SELECT [ID], [L1], [L3] FROM [SYNONYMS_OLD];
CREATE TABLE [MESHTERMS] (
    [PMID] INTEGER PRIMARY KEY,
    [MESH] TEXT,
    [MESH_MAJOR] TEXT
);
INSERT INTO [MESHTERMS] ([PMID], [MESH], [MESH_MAJOR]) SELECT [PMID], [MESH], [MESH_MAJOR] FROM [MESHTERMS_OLD];
CREATE TABLE [INFORMATION] (
    FOREIGN KEY [PMID] INTEGER PRIMARY KEY REFERENCES [MESHTERMS]([PMID]),
    [FIRST_AUTHOR] TEXT,
    [YEAR] INTEGER,
    [JOURNAL] TEXT,
    [TITLE] TEXT
);
INSERT INTO [INFORMATION] ([PMID], [FIRST_AUTHOR], [YEAR], [JOURNAL], [TITLE]) SELECT [PMID], [FIRST_AUTHOR], [YEAR], [JOURNAL], [TITLE] FROM [INFORMATION_OLD];
CREATE TABLE [IDENTIFIERS] (
    FOREIGN KEY [PMID] INTEGER REFERENCES [MESHTERMS]([PMID]),
    [ALT] TEXT
);
INSERT INTO [IDENTIFIERS] ([PMID], [ALT]) SELECT [PMID], [ALT] FROM [IDENTIFIERS_OLD];
CREATE TABLE [PMCCAPTIONS] (
    [PMC] INTEGER PRIMARY KEY,
    [FILE] TEXT,
    [CAPTION] TEXT
);
INSERT INTO [PMCCAPTIONS] ([PMC], [FILE], [CAPTIONS]) SELECT [PMC], [FILE], [CAPTION] FROM [PMCCAPTIONS_OLD];
-- COPY BUILD NEW INDEXES FOR TBDB
CREATE INDEX [IDX_NAMES_CATEGORY] ON [NAMES]([CATEGORY]);
CREATE INDEX [IDX_NAMES_TAXON] ON [NAMES]([TAXON]);
CREATE INDEX [IDX_SYNONYMS_ID] ON [SYNONYMS]([ID]);
CREATE INDEX [IDX_SYNONYMS_L1] ON [SYNONYMS]([L1]);
CREATE INDEX [IDX_SYNONYMS_L3] ON [SYNONYMS]([L3]);
CREATE INDEX [IDX_MESH_MESH_MAJOR] ON [MESHTERMS]([MESH_MAJOR]);
CREATE INDEX [IDX_IDS_PMID] ON [IDENTIFIERS]([PMID]);
CREATE INDEX [IDX_IDS_ALT] ON [IDENTIFIERS]([ALT]);
CREATE INDEX [IDX_CAPTIONS_FILE] ON [CAPTIONS]([FILE]);
-- COMMIT CHANGES
COMMIT;

-- OPTIMIZE DB AND FREE UP SPACE
ANALYZE;
PRAGMA optimize;
VACUUM;

-- REMOVE EXCLUSIVE LOCKING
PRAGMA locking_mode=NORMAL;