-- CONFIGURE DB SETTINGS
PRAGMA journal_mode=WAL;
PRAGMA synchronous=OFF;
PRAGMA foreign_keys=OFF;
PRAGMA locking_mode=EXCLUSIVE;

-- CONFIGURE DB FOR INGESTION
BEGIN IMMEDIATE;
-- DROP INDEXES FOR FASTER TRANSFER
DROP INDEX [idx_NAMES_ID];
DROP INDEX [idx_L1_NOT_NULL];
DROP INDEX [idx_L3_NOT_NULL];
DROP INDEX [idx_CATEGORIES];
-- COMMIT CHANGES
COMMIT;

-- REMOVE EXCLUSIVE LOCKING
PRAGMA locking_mode=NORMAL;