-- CONFIGURE DB SETTINGS
PRAGMA journal_mode=WAL;
PRAGMA synchronous=OFF;
PRAGMA foreign_keys=OFF;
PRAGMA locking_mode=EXCLUSIVE;

-- CONFIGURE DB FOR INGESTION
BEGIN IMMEDIATE;
-- DROP INDEXES FOR FASTER TRANSFER
DROP INDEX IF EXISTS [idx_captions_pmc_file];
-- RENAME TABLES FOR POSTGRES SCHEMA
ALTER TABLE [captions] RENAME TO [CAPTIONS];
-- RENAME COLUMNS FOR POSTGRES SCHEMA
ALTER TABLE [CAPTIONS] RENAME COLUMN [pmc] TO [PMC];
ALTER TABLE [CAPTIONS] RENAME COLUMN [file] TO [FILE];
ALTER TABLE [CAPTIONS] RENAME COLUMN [caption] TO [CAPTION];
-- COMMIT CHANGES
COMMIT;

-- OPTIMIZE DB AND FREE UP SPACE
ANALYZE;
PRAGMA optimize;
VACUUM;